name: Release

on:
  release:
    types: [published]

jobs:
  major-minor-tags:
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-update-semver@v1
        with:
          tag: ${{ github.event.release.tag_name }}