name: Release

on:
  release:
    types: [published]

jobs:
  major-minor-tags:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vweevers/additional-tags-action@v2